version: '3'

services:
  backend:
    build:
      context: ../../
      dockerfile: infra/itest/Dockerfile
    expose:
      - '3010'
    ports:
      - '3010'
    depends_on:
      - db
    environment:
      - 'db.url=postgres://root:123@db:5432/db_test'

  db:
    image: postgres
    expose:
      - '5432'
    ports:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_test
